[workspace]
resolver = "2"

members = ["shaperglot-lib", "shaperglot-cli" ]

default-members = ["shaperglot-lib", "shaperglot-cli"]

[workspace.dependencies]
read-fonts = "0"
skrifa = "0"
itertools = "0.13.0"
