name: Rust

on:
  - push
  - pull_request
  - merge_group

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching
      - name: Build
        run: cargo build
      - name: Run tests
        run: |
          cargo test --verbose --workspace 
          pip install maturin pytest
          cd shaperglot-py
          maturin build
          pip install ../target/wheels/shaperglot*.whl
          #pytest --verbose

  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching

      - name: Lint for formatting
        run: cargo fmt --all -- --check
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching
      - name: Lint for warnings
        run: cargo clippy --all-targets --all-features -- -D warnings

  deploy-binaries:
    name: Build and upload binaries
    permissions:
      contents: write
      id-token: write
    runs-on: ${{ matrix.os.os }}
    # Only build on main or tag
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        os:
          - build: linux
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: macos-m1
            os: macos-latest
            target: aarch64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
        # python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.os.target }}
          cache-key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      # - name: Set up python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python }}
      - name: Install protoc for lang repo
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.os.target }}
      - name: Decide on our version name (tag or "dev")
        id: version
        shell: bash
        run: |
          if [ -n "$GITHUB_REF" ]; then
              if [[ "$GITHUB_REF" == refs/tags/shaperglot-v* ]]; then
                  echo "VERSION=${GITHUB_REF/refs\/tags\/shaperglot-/}" >> $GITHUB_ENV
              else
                  echo "VERSION=dev" >> $GITHUB_ENV
              fi
          else
              echo "VERSION=dev" >> $GITHUB_ENV
          fi
      - name: Build archive
        shell: bash
        run: |
          # dirname="shaperglot-${{ env.VERSION }}-${{ matrix.os.target }}-py${{ matrix.python }}"
          dirname="shaperglot-${{ env.VERSION }}-${{ matrix.os.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os.os }}" = "windows-latest" ]; then
              mv "target/${{ matrix.os.target }}/release/"*.exe "$dirname"
              7z a "$dirname.zip" "$dirname"
              echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
              mv "target/${{ matrix.os.target }}/release/shaperglot" "$dirname"
              tar -czf "$dirname.tar.gz" "$dirname"
              echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET }}
          path: ${{ env.ASSET }}
      - if: contains(github.ref, 'refs/tags/shaperglot-v')
        name: Add artefact to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload shaperglot-${{ env.VERSION }} ${{ env.ASSET }}
